---
name: Check for broken links

on:
  pull_request:
    branches:
      - main

jobs:

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: LinkCheck
        uses: Consensys/github-actions/docs-link-check@main
        with:
          FILE_EXTENSION: '${{ matrix.file-extensions }}'
          CONFIG_FILE: 'mlc_config.json'
